  # Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.9'

services:
  ms-sql-server:
    env_file: 
      - .env
    container_name: OnlineDOD_SQLServer-2017
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: Express
    ports:
      - "${DB_PORT}:1433"
  app:
    env_file: 
      - .env
    container_name: OnlineDOD_dotNET-Core-5.0
    image: fri-bp-online-dod
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - DB_ADDRESS=ms-sql-server
      - DB_PORT=1433
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: on-failure:10
    depends_on:
      - ms-sql-server
    entrypoint: ["./wait-for-it.sh", "ms-sql-server:1433", "-t", "120", "--", "dotnet", "BP_OnlineDOD.Server.dll"]
    ports:
      - 4443:443
      - ${API_PORT}:80
