  # Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.9'

services:
  mysql-server:
    env_file: 
      - .env
    container_name: OnlineDOD_MySQL-Server-8.0.23
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
  app:
    env_file: 
      - .env
    container_name: OnlineDOD_dotNET-Core-5.0
    image: fri-bp-online-dod
    build:
      context: .
      dockerfile: Server/Dockerfile 
    environment:
      - DB_ADDRESS=mysql-server
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: on-failure:10
    depends_on:
      - mysql-server
    entrypoint: ["./wait-for-it.sh", "mysql-server:3306", "-t", "120", "--", "dotnet", "BP_OnlineDOD.Server.dll"]
    ports:
      - 4443:443
      - ${API_PORT}:80
