FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 1433

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["BP_OnlineDOD.Server.csproj", "./"]
RUN dotnet restore "BP_OnlineDOD.Server.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "BP_OnlineDOD.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BP_OnlineDOD.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BP_OnlineDOD.Server.dll"]
